# config/routes/calendar.yaml
calendar:
    resource: "@CalendarBundle/Resources/config/routing.yaml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"


#index:
  # path: /message/chatbot
  # controller: App\Controller\BobotController::messageAction
